from __future__ import annotations

import json
from dataclasses import dataclass

from pydantic import ValidationError
from sqlalchemy import func
from sqlalchemy.orm import Session

from waterfall.models.ms_core import MsProject, MsTask, MsTaskLink
from waterfall.models.planning import WfPlanning, WfPlanningLinkSnapshot, WfPlanningTaskSnapshot
from waterfall.models.wf_core import WfTaskEnrichment
from waterfall.schemas.projects import PlanningStructureCreate
from waterfall.services.task_references import is_task_referenced


def save_planning_structure_draft(planning: WfPlanning, payload: PlanningStructureCreate) -> None:
    planning.structure_draft_json = json.dumps(
        payload.model_dump(mode="json"), separators=(",", ":")
    )


def load_planning_structure_draft(planning: WfPlanning) -> PlanningStructureCreate | None:
    if planning.structure_draft_json is None:
        return None
    try:
        raw = json.loads(planning.structure_draft_json)
    except json.JSONDecodeError as exc:
        raise ValueError("Saved planning structure draft is invalid JSON") from exc
    try:
        return PlanningStructureCreate.model_validate(raw)
    except ValidationError as exc:
        raise ValueError("Saved planning structure draft has invalid schema") from exc


@dataclass(frozen=True)
class _GeneratedNode:
    key: str
    kind: str
    name: str
    parent_key: str | None
    outline_number: str
    outline_level: int
    position: int
    is_summary: bool = False
    is_milestone: bool = False


def _build_nodes(payload: PlanningStructureCreate) -> list[_GeneratedNode]:
    nodes: list[_GeneratedNode] = []
    seen_keys: set[str] = set()

    def add(node: _GeneratedNode) -> None:
        if node.key in seen_keys:
            raise ValueError(f"Duplicate planning key: {node.key}")
        seen_keys.add(node.key)
        nodes.append(node)

    for post_position, post in enumerate(payload.posts, start=1):
        post_key = post.key
        add(
            _GeneratedNode(
                key=post_key,
                kind="poste",
                name=post.name,
                parent_key=None,
                outline_number=str(post_position),
                outline_level=1,
                position=post_position,
                is_summary=True,
            )
        )
        for lot_position, lot in enumerate(post.lots, start=1):
            lot_key = f"{post_key}/{lot.key}"
            add(
                _GeneratedNode(
                    key=lot_key,
                    kind="lot",
                    name=lot.name,
                    parent_key=post_key,
                    outline_number=f"{post_position}.{lot_position}",
                    outline_level=2,
                    position=lot_position,
                    is_summary=True,
                )
            )
            for deliverable_position, deliverable in enumerate(lot.deliverables, start=1):
                add(
                    _GeneratedNode(
                        key=f"{lot_key}/{deliverable.key}",
                        kind="livrable",
                        name=deliverable.name,
                        parent_key=lot_key,
                        outline_number=(f"{post_position}.{lot_position}.{deliverable_position}"),
                        outline_level=3,
                        position=deliverable_position,
                    )
                )
            add(
                _GeneratedNode(
                    key=f"{lot_key}/completion",
                    kind="milestone",
                    name=f"Fin {lot.name}",
                    parent_key=lot_key,
                    outline_number=f"{post_position}.{lot_position}.{len(lot.deliverables) + 1}",
                    outline_level=3,
                    position=len(lot.deliverables) + 1,
                    is_milestone=True,
                )
            )
    return nodes


def generate_planning_structure(
    db: Session,
    project: MsProject,
    payload: PlanningStructureCreate,
) -> list[MsTask]:
    """Generate/refresh the legacy ``MsTask`` structure from a poste/lot/livrable payload.

    Additive/idempotent generation by ``structure_key``: tasks without a
    ``structure_key`` (import or manual entry) are always preserved, only
    tasks previously generated by a prior structure generation (identified by
    their ``structure_key``) are updated or removed if they no longer appear
    in the submitted structure.
    """
    nodes = _build_nodes(payload)
    keys = [node.key for node in nodes]
    existing = (
        db.query(MsTask)
        .filter(MsTask.project_id == project.id)
        .filter(MsTask.structure_key.is_not(None))
        .all()
    )
    existing_by_key = {task.structure_key: task for task in existing}
    incoming_keys = set(keys)
    removed_tasks = [task for key, task in existing_by_key.items() if key not in incoming_keys]
    for task in removed_tasks:
        if is_task_referenced(db, project_id=project.id, task_uid=task.uid, task_id=task.id):
            raise ValueError(
                f"Planning task is referenced and cannot be removed: {task.structure_key}"
            )

    removed_uids = [task.uid for task in removed_tasks]
    if removed_uids:
        db.query(MsTask).filter(
            MsTask.project_id == project.id,
            MsTask.parent_uid.in_(removed_uids),
        ).update({MsTask.parent_uid: None}, synchronize_session=False)
    for task in removed_tasks:
        db.query(MsTaskLink).filter(
            (MsTaskLink.task_uid == task.uid) | (MsTaskLink.predecessor_uid == task.uid)
        ).filter(MsTaskLink.project_id == project.id).delete(synchronize_session=False)
        db.query(WfTaskEnrichment).filter(
            WfTaskEnrichment.project_id == project.id,
            WfTaskEnrichment.task_uid == task.uid,
        ).delete(synchronize_session=False)
        task.parent_uid = None
    db.flush()
    for task in sorted(removed_tasks, key=lambda item: item.outline_level or 0, reverse=True):
        db.delete(task)
    db.flush()

    max_uid = (
        db.query(MsTask.uid)
        .filter(MsTask.project_id == project.id)
        .order_by(MsTask.uid.desc())
        .first()
    )
    max_id = (
        db.query(MsTask.id_display)
        .filter(MsTask.project_id == project.id)
        .order_by(MsTask.id_display.desc())
        .first()
    )
    next_uid = (max_uid[0] if max_uid else 0) + 1
    next_id = (max_id[0] if max_id and max_id[0] is not None else 0) + 1
    uid_by_key: dict[str, int] = {}
    tasks: list[MsTask] = []

    for node in nodes:
        task = existing_by_key.get(node.key)
        if task is None:
            task = MsTask(
                project_id=project.id,
                uid=next_uid,
                id_display=next_id,
                structure_key=node.key,
                task_type=0,
            )
            db.add(task)
            next_uid += 1
            next_id += 1
        task.structure_kind = node.kind
        task.parent_uid = uid_by_key.get(node.parent_key) if node.parent_key else None
        task.position = node.position
        task.name = node.name
        task.outline_number = node.outline_number
        task.outline_level = node.outline_level
        task.is_summary = node.is_summary
        task.is_milestone = node.is_milestone
        tasks.append(task)
        uid_by_key[node.key] = task.uid

    db.flush()
    deliverables_by_lot_key = {
        f"{post.key}/{lot.key}": lot.deliverables for post in payload.posts for lot in post.lots
    }
    for node in nodes:
        if node.kind != "milestone" or node.parent_key is None:
            continue
        for deliverable in deliverables_by_lot_key[node.parent_key]:
            link_values = {
                "project_id": project.id,
                "task_uid": uid_by_key[node.key],
                "predecessor_uid": uid_by_key[f"{node.parent_key}/{deliverable.key}"],
                "link_type": 1,
                "lag_tenth_minute": 0,
                "lag_format": 7,
            }
            if not db.query(MsTaskLink.id).filter_by(**link_values).first():
                db.add(MsTaskLink(**link_values))
    db.flush()
    return tasks


def _fetch_and_prepare_existing_tasks(
    db: Session,
    planning: WfPlanning,
    project: MsProject,
) -> tuple[
    list[WfPlanningTaskSnapshot],
    dict[str, WfPlanningTaskSnapshot],
    list[WfPlanningTaskSnapshot] | None,
    int,
]:
    """Load existing and source tasks with existing_by_key map and max_uid."""
    existing = (
        db.query(WfPlanningTaskSnapshot)
        .filter(WfPlanningTaskSnapshot.planning_id == planning.id)
        .all()
    )
    existing_by_key = {
        task.structure_key: task for task in existing if task.structure_key is not None
    }
    source = None
    if not existing and project.displayed_planning_id not in (None, planning.id):
        source = (
            db.query(WfPlanningTaskSnapshot)
            .filter(WfPlanningTaskSnapshot.planning_id == project.displayed_planning_id)
            .all()
        )
        existing_by_key.update(
            {task.structure_key: task for task in source if task.structure_key is not None}
        )

    max_uid = (
        db.query(func.max(WfPlanningTaskSnapshot.uid))
        .filter(WfPlanningTaskSnapshot.planning_id == planning.id)
        .scalar()
        or 0
    )
    if source:
        max_uid = max(max_uid, max(task.uid for task in source))

    return existing, existing_by_key, source, max_uid


def _delete_obsolete_tasks_and_links(
    db: Session,
    planning: WfPlanning,
    existing: list[WfPlanningTaskSnapshot],
    incoming_keys: set[str],
) -> None:
    """Delete obsolete links and tasks that are no longer in the incoming structure."""
    links = (
        db.query(WfPlanningLinkSnapshot)
        .filter(WfPlanningLinkSnapshot.planning_id == planning.id)
        .all()
    )
    existing_uids = {
        task.uid
        for task in existing
        if task.structure_key is None or task.structure_key in incoming_keys
    }
    for link in links:
        if link.task_uid not in existing_uids or link.predecessor_uid not in existing_uids:
            db.delete(link)

    removed_ids = [
        task.id
        for task in existing
        if task.structure_key is not None and task.structure_key not in incoming_keys
    ]

    db.query(WfPlanningTaskSnapshot).filter(
        WfPlanningTaskSnapshot.planning_id == planning.id
    ).update({WfPlanningTaskSnapshot.parent_uid: None}, synchronize_session=False)
    db.flush()

    if removed_ids:
        db.query(WfPlanningTaskSnapshot).filter(WfPlanningTaskSnapshot.id.in_(removed_ids)).delete(
            synchronize_session=False
        )
    db.flush()


def _create_or_update_node_snapshots(
    db: Session,
    nodes: list[_GeneratedNode],
    existing_by_key: dict[str, WfPlanningTaskSnapshot],
    planning: WfPlanning,
    max_uid: int,
) -> tuple[list[WfPlanningTaskSnapshot], dict[str, int]]:
    """Create or update snapshot tasks for each node."""
    uid_by_key: dict[str, int] = {}
    snapshots: list[WfPlanningTaskSnapshot] = []

    for node in nodes:
        task = existing_by_key.get(node.key)
        if task is None:
            max_uid += 1
            task = WfPlanningTaskSnapshot(
                planning_id=planning.id,
                uid=max_uid,
                id_display=max_uid,
                structure_key=node.key,
                notes=None,
            )
            db.add(task)
        elif task.planning_id != planning.id:
            source_task = task
            task = WfPlanningTaskSnapshot(
                planning_id=planning.id,
                uid=source_task.uid,
                id_display=source_task.id_display,
                structure_key=node.key,
                notes=source_task.notes,
            )
            db.add(task)
        task.structure_kind = node.kind
        task.parent_uid = uid_by_key.get(node.parent_key) if node.parent_key else None
        task.position = node.position
        task.name = node.name
        task.task_type = 0
        task.outline_number = node.outline_number
        task.outline_level = node.outline_level
        task.is_summary = node.is_summary
        task.is_milestone = node.is_milestone
        snapshots.append(task)
        uid_by_key[node.key] = task.uid

    db.flush()

    return snapshots, uid_by_key


def _copy_links_from_source(
    db: Session,
    source: list[WfPlanningTaskSnapshot] | None,
    nodes: list[_GeneratedNode],
    planning: WfPlanning,
    project: MsProject,
    uid_by_key: dict[str, int],
) -> None:
    """Copy links from source planning if it exists."""
    if not source:
        return

    source_links = (
        db.query(WfPlanningLinkSnapshot)
        .filter(WfPlanningLinkSnapshot.planning_id == project.displayed_planning_id)
        .all()
    )
    source_uid_by_key = {task.structure_key: task.uid for task in source}
    source_uid_to_new_uid = {
        source_uid_by_key[node.key]: uid_by_key[node.key]
        for node in nodes
        if node.key in source_uid_by_key
    }
    for link in source_links:
        task_uid = source_uid_to_new_uid.get(link.task_uid)
        predecessor_uid = source_uid_to_new_uid.get(link.predecessor_uid)
        if task_uid is None or predecessor_uid is None:
            continue
        if (
            not db.query(WfPlanningLinkSnapshot.id)
            .filter_by(
                planning_id=planning.id,
                task_uid=task_uid,
                predecessor_uid=predecessor_uid,
                link_type=link.link_type,
            )
            .first()
        ):
            db.add(
                WfPlanningLinkSnapshot(
                    planning_id=planning.id,
                    task_uid=task_uid,
                    predecessor_uid=predecessor_uid,
                    link_type=link.link_type,
                    lag_tenth_minute=link.lag_tenth_minute,
                    lag_format=link.lag_format,
                )
            )


def _create_deliverable_milestone_links(
    db: Session,
    nodes: list[_GeneratedNode],
    payload: PlanningStructureCreate,
    planning: WfPlanning,
    uid_by_key: dict[str, int],
) -> None:
    """Create links from deliverables to milestones."""
    deliverables_by_lot_key = {
        f"{post.key}/{lot.key}": lot.deliverables for post in payload.posts for lot in post.lots
    }
    for node in nodes:
        if node.kind != "milestone" or node.parent_key is None:
            continue
        for deliverable in deliverables_by_lot_key[node.parent_key]:
            link_values = {
                "planning_id": planning.id,
                "task_uid": uid_by_key[node.key],
                "predecessor_uid": uid_by_key[f"{node.parent_key}/{deliverable.key}"],
                "link_type": 1,
                "lag_tenth_minute": 0,
                "lag_format": 7,
            }
            if not db.query(WfPlanningLinkSnapshot.id).filter_by(**link_values).first():
                db.add(WfPlanningLinkSnapshot(**link_values))


def generate_planning_snapshot(
    db: Session,
    project: MsProject,
    payload: PlanningStructureCreate,
    planning: WfPlanning,
) -> list[WfPlanningTaskSnapshot]:
    """Generate/refresh a draft planning's task snapshots from a poste/lot/livrable payload.

    Additive/idempotent generation by ``structure_key``: tasks without a
    ``structure_key`` (import or manual entry) are always preserved, only
    tasks previously generated by a prior structure generation (identified by
    their ``structure_key``) are updated or removed if they no longer appear
    in the submitted structure.
    """
    nodes = _build_nodes(payload)
    existing, existing_by_key, source, max_uid = _fetch_and_prepare_existing_tasks(
        db, planning, project
    )

    incoming_keys = {node.key for node in nodes}
    _delete_obsolete_tasks_and_links(db, planning, existing, incoming_keys)

    snapshots, uid_by_key = _create_or_update_node_snapshots(
        db, nodes, existing_by_key, planning, max_uid
    )

    _copy_links_from_source(db, source, nodes, planning, project, uid_by_key)

    _create_deliverable_milestone_links(db, nodes, payload, planning, uid_by_key)

    db.flush()
    return snapshots
