"""Pure domain of the revision model -- E14-02 test bench, E14-04 tree logic.

Transcribes ``docs/revision-v0.1-specification.md``: a ``work_item`` is the stable
identity of an element of work across versions, a :class:`ProjectRevision` carries
the tree of a version exactly once, a node is a position in that tree, and the
planning and the cost are two facets hung on the same node.

The **lotissement** sits deliberately outside all of that: it is project data, not
versioned and not frozen by a validated revision (INV-26, Règle 4). See
:mod:`waterfall.domain.revision.work_breakdown`.

**Architecture rule, enforced by a test**: nothing under this package may import
``sqlalchemy``, ``fastapi`` or ``waterfall.models``, read a file, open a socket or
look at a clock (timestamps are always passed in). The persistence service of
E14-04 loads a revision, delegates every tree operation here, and writes back.
"""

from waterfall.domain.revision import facets
from waterfall.domain.revision.entities import (
    BreakdownEntry,
    BreakdownKind,
    CalendarSource,
    CostFacet,
    CostNature,
    FrozenLine,
    NodeLink,
    PlanFacet,
    Project,
    ProjectRevision,
    ProjectStatus,
    RevisionKind,
    RevisionNode,
    RevisionStatus,
    Role,
    SkeletonFingerprint,
    SupplyStatus,
    WorkItem,
    WorkItemKind,
)
from waterfall.domain.revision.errors import (
    CrossRevisionError,
    DuplicateWorkItemError,
    ExternalUidError,
    FacetContractError,
    FacetPlacementError,
    ImmutableRevisionError,
    ImportStructureError,
    LinkError,
    NotFoundError,
    PositionError,
    ProjectMismatchError,
    RevisionDomainError,
    RevisionLifecycleError,
    SelectionError,
    TreeCycleError,
    WorkBreakdownError,
)
from waterfall.domain.revision.facets import (
    assign_role,
    clear_task_calendar_override,
    rename_task,
    set_cost_comment,
    set_cost_hours,
    set_cost_label,
    set_cost_planned_date,
    set_cost_quantity,
    set_cost_unit_cost,
    set_supply_status,
    set_task_calendar_manually,
    set_task_dates,
    set_task_duration,
)
from waterfall.domain.revision.invariants import (
    InvariantViolation,
    check_all_invariants,
    check_invariants,
    violated_invariant_ids,
)
from waterfall.domain.revision.lifecycle import (
    copy_revision,
    create_revision,
    validate_revision,
)
from waterfall.domain.revision.reconciliation import (
    ReconciliationEntry,
    reconcile_forecast_to_budget,
)
from waterfall.domain.revision.reimport import (
    ImportDiff,
    ImportDiffItem,
    ImportedTask,
    apply_reimport,
    plan_reimport,
)
from waterfall.domain.revision.structure import (
    ancestors_of,
    bearing_work_item_id,
    children_of,
    depth_first,
    node_by_work_item,
    resolve_bearing_task,
    subtree_ids,
)
from waterfall.domain.revision.tree import (
    CostLoss,
    DeletionReport,
    add_cost_line,
    add_link,
    add_task,
    carries_labor,
    check_external_uid_available,
    cost_losses_of,
    create_work_item,
    delete_nodes,
    describe_cost_losses,
    indent_nodes,
    insert_node,
    links_of,
    move_nodes,
    move_nodes_down,
    move_nodes_up,
    outdent_nodes,
    selection_roots,
)
from waterfall.domain.revision.work_breakdown import (
    breakdown_changed_since_generation,
    can_regenerate_skeleton,
    generate_skeleton,
    regenerate_skeleton,
    save_work_breakdown,
    skeleton_fingerprint_of,
)

__all__ = [
    "BreakdownEntry",
    "BreakdownKind",
    "CalendarSource",
    "CostFacet",
    "CostLoss",
    "CostNature",
    "CrossRevisionError",
    "DeletionReport",
    "DuplicateWorkItemError",
    "ExternalUidError",
    "FacetContractError",
    "FacetPlacementError",
    "FrozenLine",
    "ImmutableRevisionError",
    "ImportDiff",
    "ImportDiffItem",
    "ImportStructureError",
    "ImportedTask",
    "InvariantViolation",
    "LinkError",
    "NodeLink",
    "NotFoundError",
    "PlanFacet",
    "PositionError",
    "Project",
    "ProjectMismatchError",
    "ProjectRevision",
    "ProjectStatus",
    "ReconciliationEntry",
    "RevisionDomainError",
    "RevisionKind",
    "RevisionLifecycleError",
    "RevisionNode",
    "RevisionStatus",
    "Role",
    "SelectionError",
    "SkeletonFingerprint",
    "SupplyStatus",
    "TreeCycleError",
    "WorkBreakdownError",
    "WorkItem",
    "WorkItemKind",
    "add_cost_line",
    "add_link",
    "add_task",
    "ancestors_of",
    "apply_reimport",
    "assign_role",
    "bearing_work_item_id",
    "breakdown_changed_since_generation",
    "can_regenerate_skeleton",
    "carries_labor",
    "check_all_invariants",
    "check_external_uid_available",
    "check_invariants",
    "children_of",
    "clear_task_calendar_override",
    "copy_revision",
    "cost_losses_of",
    "create_revision",
    "create_work_item",
    "delete_nodes",
    "depth_first",
    "describe_cost_losses",
    "facets",
    "generate_skeleton",
    "indent_nodes",
    "insert_node",
    "links_of",
    "move_nodes",
    "move_nodes_down",
    "move_nodes_up",
    "node_by_work_item",
    "outdent_nodes",
    "plan_reimport",
    "reconcile_forecast_to_budget",
    "regenerate_skeleton",
    "rename_task",
    "resolve_bearing_task",
    "save_work_breakdown",
    "selection_roots",
    "set_cost_comment",
    "set_cost_hours",
    "set_cost_label",
    "set_cost_planned_date",
    "set_cost_quantity",
    "set_cost_unit_cost",
    "set_supply_status",
    "set_task_calendar_manually",
    "set_task_dates",
    "set_task_duration",
    "skeleton_fingerprint_of",
    "subtree_ids",
    "validate_revision",
    "violated_invariant_ids",
]
