services:
  # db
  db_service:
    image: postgres:16
    environment:
      POSTGRES_USER: staging
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staging
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staging -d staging"]
      interval: 10s
      timeout: 5s
      retries: 5

  guardian_service:
    build: ./services/guardian_service
    environment:
      - FLASK_ENV=staging
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://staging:password@db_service/guardian_staging
      - JWT_SECRET=super-secret-jwt-key
    ports:
      - "5003:5000"
    depends_on:
      db_service:
        condition: service_healthy
    volumes:
      - ./services/guardian_service:/app

  identity_service:
    build: ./services/identity_service
    environment:
      - FLASK_ENV=staging
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://staging:password@db_service/identity_staging
      - INTERNAL_AUTH_TOKEN=staging-internal-secret
      - JWT_SECRET=super-secret-jwt-key
    ports:
      - "5002:5000"
    depends_on:
      db_service:
        condition: service_healthy
      guardian_service:
        condition: service_started
    volumes:
      - ./services/identity_service:/app

  auth_service:
    build: ./services/auth_service
    environment:
      - FLASK_ENV=staging
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://staging:password@db_service/auth_staging
      - INTERNAL_AUTH_TOKEN=staging-internal-secret
      - JWT_SECRET=super-secret-jwt-key
    ports:
      - "5001:5000"
    depends_on:
      db_service:
        condition: service_healthy
      identity_service:
        condition: service_started
    volumes:
      - ./services/auth_service:/app

  web_service:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - auth_service
      - identity_service
      - guardian_service
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - MOCK_API=false
      - OFFLINE_MODE=false
      - AUTH_SERVICE_URL=http://auth_service:5000
      - IDENTITY_SERVICE_URL=http://identity_service:5000
      - GUARDIAN_SERVICE_URL=http://guardian_service:5000

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /foo/swagger.json
    volumes:
      - ./swagger.json:/foo/swagger.json

volumes:
  db_data:
  pgadmin_data: