"use client";

import type { FormEventHandler } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { CostType } from "@/lib/backend";

export type CostTypesTableProps = { items: CostType[]; code: string; name: string; kind: CostType["kind"]; draft: string; editingId: number | null; busy: boolean; labels: Record<CostType["kind"], string>; onSubmit: FormEventHandler<HTMLFormElement>; onCodeChange: (value: string) => void; onNameChange: (value: string) => void; onKindChange: (value: CostType["kind"]) => void; onStartEdit: (item: CostType) => void; onDraftChange: (value: string) => void; onSave: (item: CostType) => void; onCancel: () => void; onToggle: (item: CostType) => void };

export function CostTypesTable(props: CostTypesTableProps) {
  return <Card className="mt-4"><CardHeader><CardTitle>Types de coût</CardTitle></CardHeader><CardContent><form onSubmit={props.onSubmit}><Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Nom</TableHead><TableHead>Comportement</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell><Input aria-label="Code du nouveau type" value={props.code} onChange={(event) => props.onCodeChange(event.target.value)} required /></TableCell><TableCell><Input aria-label="Nom du nouveau type" value={props.name} onChange={(event) => props.onNameChange(event.target.value)} required /></TableCell><TableCell><select aria-label="Comportement du nouveau type" className="h-8 w-full rounded-md border border-input bg-background px-2 text-sm" value={props.kind} onChange={(event) => props.onKindChange(event.target.value as CostType["kind"])}><option value="labor">{props.labels.labor}</option><option value="supply">{props.labels.supply}</option><option value="other">{props.labels.other}</option></select></TableCell><TableCell className="text-right"><Button size="sm" disabled={props.busy} type="submit">Ajouter</Button></TableCell></TableRow>{props.items.map((item) => { const editing = props.editingId === item.id; return <TableRow key={item.id} className={item.is_active ? undefined : "opacity-55"}><TableCell className="font-medium">{item.code}</TableCell><TableCell>{editing ? <Input aria-label={`Nom de ${item.code}`} value={props.draft} onChange={(event) => props.onDraftChange(event.target.value)} /> : item.name}</TableCell><TableCell>{props.labels[item.kind]}</TableCell><TableCell><div className="flex justify-end gap-2">{item.is_active && (editing ? <><Button size="sm" type="button" disabled={props.busy} onClick={() => props.onSave(item)}>Enregistrer</Button><Button size="sm" variant="outline" type="button" onClick={props.onCancel}>Annuler</Button></> : <Button size="sm" variant="outline" type="button" onClick={() => props.onStartEdit(item)}>Modifier</Button>)}<Button size="sm" variant="outline" type="button" disabled={props.busy} onClick={() => props.onToggle(item)}>{item.is_active ? "Désactiver" : "Réactiver"}</Button></div></TableCell></TableRow>; })}</TableBody></Table></form></CardContent></Card>;
}
