"""initial schema

Revision ID: 2a6eb07ee231
Revises:
Create Date: 2026-08-23 22:46:12.895031

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20260823_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ms_project",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("external_uid", sa.String(length=16), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("source_version", sa.SmallInteger(), nullable=False),
        sa.Column("save_version_out", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schedule_from_start", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finish_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calendar_uid", sa.Integer(), nullable=True),
        sa.Column("minutes_per_day", sa.Integer(), nullable=False),
        sa.Column("minutes_per_week", sa.Integer(), nullable=False),
        sa.Column("days_per_month", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("planning_reference_id", sa.Integer(), nullable=True),
        sa.Column("displayed_planning_id", sa.Integer(), nullable=True),
        sa.Column("reference_estimate_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('cree', 'initialise', 'en_reponse_appel_offre', 'perdu', "
            "'en_cours', 'termine', 'abandonne')",
            name="ck_ms_project_status",
        ),
        sa.CheckConstraint(
            "(schedule_from_start = true AND start_date IS NOT NULL) OR "
            "(schedule_from_start = false AND finish_date IS NOT NULL)",
            name="ck_ms_project_schedule_dates",
        ),
        sa.CheckConstraint(
            "save_version_out IN (14, 15, 16)", name="ck_ms_project_save_version_out"
        ),
        sa.CheckConstraint(
            "source_version IN (2010, 2013, 2016)", name="ck_ms_project_source_version"
        ),
        sa.ForeignKeyConstraint(
            ["id", "displayed_planning_id"],
            ["wf_planning.project_id", "wf_planning.id"],
            name="fk_ms_project_displayed_planning",
        ),
        sa.ForeignKeyConstraint(
            ["id", "planning_reference_id"],
            ["wf_planning.project_id", "wf_planning.id"],
            name="fk_ms_project_planning_reference",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_estimate_id"], ["wf_estimate.id"], name="fk_ms_project_reference_estimate"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ms_project_name", "ms_project", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "wf_cost_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('labor', 'supply', 'other')", name="ck_wf_cost_type_kind"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "wf_estimate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("planning_id", sa.Integer(), nullable=True),
        sa.Column("reference_estimate_id", sa.Integer(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('initial', 'contract_reference', 'forecast_remaining')",
            name="ck_wf_estimate_kind",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'validated', 'superseded', 'archived')",
            name="ck_wf_estimate_status",
        ),
        sa.CheckConstraint("version_number > 0", name="ck_wf_estimate_version"),
        sa.ForeignKeyConstraint(
            ["planning_id"],
            ["wf_planning.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_estimate_id"],
            ["wf_estimate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version_number", name="uq_wf_estimate_project_version"),
    )
    op.create_table(
        "wf_inflation_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("coefficient", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("coefficient > 0", name="ck_wf_inflation_rate_coefficient"),
        sa.CheckConstraint("year >= 2000", name="ck_wf_inflation_rate_year"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year"),
    )
    op.create_table(
        "wf_planning",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("structure_draft_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'validated', 'superseded')", name="ck_wf_planning_status"
        ),
        sa.CheckConstraint("version_number > 0", name="ck_wf_planning_version"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "id", name="uq_wf_planning_project_id"),
        sa.UniqueConstraint("project_id", "version_number", name="uq_wf_planning_project_version"),
    )
    op.create_table(
        "wf_resource_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["wf_resource_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_wf_resource_node_code"),
    )
    op.create_index("idx_wf_resource_node_parent", "wf_resource_node", ["parent_id"], unique=False)
    op.create_table(
        "ms_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("id_display", sa.Integer(), nullable=True),
        sa.Column("structure_key", sa.String(length=128), nullable=True),
        sa.Column("structure_kind", sa.String(length=16), nullable=True),
        sa.Column("parent_uid", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("task_type", sa.SmallInteger(), nullable=True),
        sa.Column("outline_number", sa.String(length=512), nullable=True),
        sa.Column("outline_level", sa.Integer(), nullable=True),
        sa.Column("wbs", sa.String(length=255), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("duration_format", sa.SmallInteger(), nullable=True),
        sa.Column("work_minutes", sa.Integer(), nullable=True),
        sa.Column("percent_complete", sa.SmallInteger(), nullable=True),
        sa.Column("is_summary", sa.Boolean(), nullable=False),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=True),
        sa.Column("calendar_uid", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "structure_kind IN ('poste', 'lot', 'livrable', 'milestone', 'task') "
            "OR structure_kind IS NULL",
            name="ck_ms_task_structure_kind",
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes >= 0",
            name="ck_ms_task_duration_non_negative",
        ),
        sa.CheckConstraint(
            "parent_uid IS NULL OR parent_uid > 0", name="ck_ms_task_parent_uid_positive"
        ),
        sa.CheckConstraint(
            "percent_complete BETWEEN 0 AND 100 OR percent_complete IS NULL",
            name="ck_ms_task_percent_complete",
        ),
        sa.CheckConstraint("position IS NULL OR position > 0", name="ck_ms_task_position_positive"),
        sa.CheckConstraint("task_type IN (0, 1, 2) OR task_type IS NULL", name="ck_ms_task_type"),
        sa.CheckConstraint(
            "work_minutes IS NULL OR work_minutes >= 0", name="ck_ms_task_work_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "parent_uid"],
            ["ms_task.project_id", "ms_task.uid"],
            name="fk_ms_task_parent",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "structure_key", name="uq_ms_task_project_structure_key"),
        sa.UniqueConstraint("project_id", "uid", name="uq_ms_task_project_uid"),
    )
    op.create_index(
        "idx_ms_task_project_id_display", "ms_task", ["project_id", "id_display"], unique=False
    )
    op.create_index(
        "idx_ms_task_project_outline",
        "ms_task",
        ["project_id", "outline_level", "outline_number"],
        unique=False,
    )
    op.create_table(
        "wf_cost_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cost_type_id", sa.Integer(), nullable=False),
        sa.Column("accounting_code", sa.String(length=64), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_type_id"],
            ["wf_cost_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accounting_code"),
    )
    op.create_table(
        "wf_import_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("import_mode", sa.String(length=16), nullable=False),
        sa.Column("source_filename", sa.String(length=512), nullable=False),
        sa.Column("source_storage_path", sa.String(length=1024), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("log_json", sa.String(), nullable=True),
        sa.CheckConstraint("import_mode IN ('standard', 'full')", name="ck_wf_import_batch_mode"),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'success', 'failed')",
            name="ck_wf_import_batch_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wf_planning_task_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planning_id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("id_display", sa.Integer(), nullable=True),
        sa.Column("structure_key", sa.String(length=128), nullable=True),
        sa.Column("structure_kind", sa.String(length=16), nullable=True),
        sa.Column("parent_uid", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("task_type", sa.SmallInteger(), nullable=True),
        sa.Column("outline_number", sa.String(length=512), nullable=True),
        sa.Column("outline_level", sa.Integer(), nullable=True),
        sa.Column("wbs", sa.String(length=255), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("duration_format", sa.SmallInteger(), nullable=True),
        sa.Column("work_minutes", sa.Integer(), nullable=True),
        sa.Column("percent_complete", sa.SmallInteger(), nullable=True),
        sa.Column("is_summary", sa.Boolean(), nullable=False),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=True),
        sa.Column("calendar_uid", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "structure_kind IN ('poste', 'lot', 'livrable', 'milestone', 'task') "
            "OR structure_kind IS NULL",
            name="ck_wf_planning_task_snapshot_structure_kind",
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes >= 0",
            name="ck_wf_planning_task_snapshot_duration",
        ),
        sa.CheckConstraint(
            "parent_uid IS NULL OR parent_uid > 0", name="ck_wf_planning_task_snapshot_parent_uid"
        ),
        sa.CheckConstraint(
            "percent_complete BETWEEN 0 AND 100 OR percent_complete IS NULL",
            name="ck_wf_planning_task_snapshot_percent_complete",
        ),
        sa.CheckConstraint(
            "position IS NULL OR position > 0", name="ck_wf_planning_task_snapshot_position"
        ),
        sa.CheckConstraint(
            "task_type IN (0, 1, 2) OR task_type IS NULL", name="ck_wf_planning_task_snapshot_type"
        ),
        sa.CheckConstraint(
            "work_minutes IS NULL OR work_minutes >= 0", name="ck_wf_planning_task_snapshot_work"
        ),
        sa.ForeignKeyConstraint(
            ["planning_id", "parent_uid"],
            ["wf_planning_task_snapshot.planning_id", "wf_planning_task_snapshot.uid"],
            name="fk_wf_planning_task_snapshot_parent",
        ),
        sa.ForeignKeyConstraint(
            ["planning_id"],
            ["wf_planning.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_id", "structure_key", name="uq_wf_planning_task_snapshot_structure_key"
        ),
        sa.UniqueConstraint("planning_id", "uid", name="uq_wf_planning_task_snapshot_uid"),
    )
    op.create_table(
        "ms_task_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_uid", sa.Integer(), nullable=False),
        sa.Column("predecessor_uid", sa.Integer(), nullable=False),
        sa.Column("link_type", sa.SmallInteger(), nullable=False),
        sa.Column("lag_tenth_minute", sa.Integer(), nullable=True),
        sa.Column("lag_format", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint("link_type IN (0, 1, 2, 3)", name="ck_ms_task_link_type"),
        sa.ForeignKeyConstraint(
            ["project_id", "predecessor_uid"],
            ["ms_task.project_id", "ms_task.uid"],
            name="fk_ms_task_link_pred",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "task_uid"],
            ["ms_task.project_id", "ms_task.uid"],
            name="fk_ms_task_link_task",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "task_uid", "predecessor_uid", "link_type", name="uq_ms_task_link"
        ),
    )
    op.create_index(
        "idx_ms_task_link_predecessor_uid",
        "ms_task_link",
        ["project_id", "predecessor_uid"],
        unique=False,
    )
    op.create_index(
        "idx_ms_task_link_task_uid", "ms_task_link", ["project_id", "task_uid"], unique=False
    )
    op.create_table(
        "wf_cost_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cost_category_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("hourly_rate >= 0", name="ck_wf_cost_rate_hourly_rate"),
        sa.CheckConstraint("year >= 2000", name="ck_wf_cost_rate_year"),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["wf_cost_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cost_category_id", "year", name="uq_wf_cost_rate_category_year"),
    )
    op.create_index("idx_wf_cost_rate_year", "wf_cost_rate", ["year"], unique=False)
    op.create_table(
        "wf_estimate_cost_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("cost_type_id", sa.Integer(), nullable=False),
        sa.Column("cost_category_id", sa.Integer(), nullable=False),
        sa.Column("cost_type_code", sa.String(length=32), nullable=False),
        sa.Column("accounting_code", sa.String(length=64), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("purchase_cost", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("supply_status", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "supply_status IN ('planned', 'ordered', 'received', 'cancelled') "
            "OR supply_status IS NULL",
            name="ck_wf_estimate_cost_line_supply_status",
        ),
        sa.CheckConstraint("purchase_cost >= 0", name="ck_wf_estimate_cost_line_purchase_cost"),
        sa.CheckConstraint("quantity > 0", name="ck_wf_estimate_cost_line_quantity"),
        sa.CheckConstraint("unit_cost >= 0", name="ck_wf_estimate_cost_line_unit_cost"),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["wf_cost_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cost_type_id"],
            ["wf_cost_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["wf_estimate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ms_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_wf_estimate_cost_line_category",
        "wf_estimate_cost_line",
        ["cost_category_id"],
        unique=False,
    )
    op.create_index(
        "idx_wf_estimate_cost_line_estimate", "wf_estimate_cost_line", ["estimate_id"], unique=False
    )
    op.create_index(
        "idx_wf_estimate_cost_line_task", "wf_estimate_cost_line", ["task_id"], unique=False
    )
    op.create_table(
        "wf_estimate_task_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("parent_task_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(length=512), nullable=False),
        sa.Column("outline_number", sa.String(length=512), nullable=True),
        sa.Column("outline_level", sa.Integer(), nullable=True),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["wf_estimate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["ms_task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ms_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("estimate_id", "task_id", name="uq_wf_estimate_task_row"),
    )
    op.create_index(
        "idx_wf_estimate_task_row_estimate_position",
        "wf_estimate_task_row",
        ["estimate_id", "position"],
        unique=False,
    )
    op.create_table(
        "wf_excel_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("log_json", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed')", name="ck_wf_excel_import_status"
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["wf_import_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wf_planning_link_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planning_id", sa.Integer(), nullable=False),
        sa.Column("task_uid", sa.Integer(), nullable=False),
        sa.Column("predecessor_uid", sa.Integer(), nullable=False),
        sa.Column("link_type", sa.SmallInteger(), nullable=False),
        sa.Column("lag_tenth_minute", sa.Integer(), nullable=True),
        sa.Column("lag_format", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint("link_type IN (0, 1, 2, 3)", name="ck_wf_planning_link_snapshot_type"),
        sa.ForeignKeyConstraint(
            ["planning_id", "predecessor_uid"],
            ["wf_planning_task_snapshot.planning_id", "wf_planning_task_snapshot.uid"],
            name="fk_wf_planning_link_snapshot_pred",
        ),
        sa.ForeignKeyConstraint(
            ["planning_id", "task_uid"],
            ["wf_planning_task_snapshot.planning_id", "wf_planning_task_snapshot.uid"],
            name="fk_wf_planning_link_snapshot_task",
        ),
        sa.ForeignKeyConstraint(
            ["planning_id"],
            ["wf_planning.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_id",
            "task_uid",
            "predecessor_uid",
            "link_type",
            name="uq_wf_planning_link_snapshot",
        ),
    )
    op.create_table(
        "wf_resource_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("cost_category_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["wf_cost_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["wf_resource_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_wf_resource_role_code"),
    )
    op.create_index("idx_wf_resource_role_node", "wf_resource_role", ["node_id"], unique=False)
    op.create_table(
        "wf_task_enrichment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_uid", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "task_uid"],
            ["ms_task.project_id", "ms_task.uid"],
            name="fk_wf_task_enrichment_task",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "task_uid", name="uq_wf_task_enrichment_task"),
    )
    op.create_index(
        "idx_wf_task_enrichment_task",
        "wf_task_enrichment",
        ["project_id", "task_uid"],
        unique=False,
    )
    op.create_table(
        "wf_charge_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_uid", sa.Integer(), nullable=False),
        sa.Column("load_minutes", sa.Integer(), nullable=False),
        sa.Column("budget_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("source_excel_import_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("load_minutes >= 0", name="ck_wf_charge_line_load_non_negative"),
        sa.ForeignKeyConstraint(
            ["project_id", "task_uid"],
            ["ms_task.project_id", "ms_task.uid"],
            name="fk_wf_charge_line_task",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["ms_project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_excel_import_id"],
            ["wf_excel_import.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_wf_charge_line_task", "wf_charge_line", ["project_id", "task_uid"], unique=False
    )
    op.create_table(
        "wf_estimate_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("task_name", sa.String(length=512), nullable=False),
        sa.Column("role_code", sa.String(length=64), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("accounting_code", sa.String(length=64), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hours", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("inflation_coefficient", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("budget_cost", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.CheckConstraint("budget_cost >= 0", name="ck_wf_estimate_line_budget"),
        sa.CheckConstraint("hourly_rate >= 0", name="ck_wf_estimate_line_rate"),
        sa.CheckConstraint("hours >= 0", name="ck_wf_estimate_line_hours"),
        sa.CheckConstraint("inflation_coefficient > 0", name="ck_wf_estimate_line_inflation"),
        sa.CheckConstraint("quantity > 0", name="ck_wf_estimate_line_quantity"),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["wf_estimate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["wf_resource_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ms_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_wf_estimate_line_estimate", "wf_estimate_line", ["estimate_id"], unique=False
    )
    op.create_index("idx_wf_estimate_line_role", "wf_estimate_line", ["role_id"], unique=False)
    op.create_index("idx_wf_estimate_line_task", "wf_estimate_line", ["task_id"], unique=False)
    op.create_table(
        "wf_role_capacity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("person_count", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("available_hours", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("available_hours >= 0", name="ck_wf_role_capacity_hours"),
        sa.CheckConstraint("person_count >= 0", name="ck_wf_role_capacity_person_count"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["wf_resource_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", name="uq_wf_role_capacity_role"),
    )
    op.create_table(
        "wf_task_role_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hours", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("hours >= 0", name="ck_wf_task_role_hours"),
        sa.CheckConstraint("quantity > 0", name="ck_wf_task_role_quantity"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["wf_resource_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ms_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "role_id", name="uq_wf_task_role_assignment"),
    )
    op.create_index(
        "idx_wf_task_role_assignment_role", "wf_task_role_assignment", ["role_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wf_task_role_assignment_role", table_name="wf_task_role_assignment")
    op.drop_table("wf_task_role_assignment")
    op.drop_table("wf_role_capacity")
    op.drop_index("idx_wf_estimate_line_task", table_name="wf_estimate_line")
    op.drop_index("idx_wf_estimate_line_role", table_name="wf_estimate_line")
    op.drop_index("idx_wf_estimate_line_estimate", table_name="wf_estimate_line")
    op.drop_table("wf_estimate_line")
    op.drop_index("idx_wf_charge_line_task", table_name="wf_charge_line")
    op.drop_table("wf_charge_line")
    op.drop_index("idx_wf_task_enrichment_task", table_name="wf_task_enrichment")
    op.drop_table("wf_task_enrichment")
    op.drop_index("idx_wf_resource_role_node", table_name="wf_resource_role")
    op.drop_table("wf_resource_role")
    op.drop_table("wf_planning_link_snapshot")
    op.drop_table("wf_excel_import")
    op.drop_index("idx_wf_estimate_task_row_estimate_position", table_name="wf_estimate_task_row")
    op.drop_table("wf_estimate_task_row")
    op.drop_index("idx_wf_estimate_cost_line_task", table_name="wf_estimate_cost_line")
    op.drop_index("idx_wf_estimate_cost_line_estimate", table_name="wf_estimate_cost_line")
    op.drop_index("idx_wf_estimate_cost_line_category", table_name="wf_estimate_cost_line")
    op.drop_table("wf_estimate_cost_line")
    op.drop_index("idx_wf_cost_rate_year", table_name="wf_cost_rate")
    op.drop_table("wf_cost_rate")
    op.drop_index("idx_ms_task_link_task_uid", table_name="ms_task_link")
    op.drop_index("idx_ms_task_link_predecessor_uid", table_name="ms_task_link")
    op.drop_table("ms_task_link")
    op.drop_table("wf_planning_task_snapshot")
    op.drop_table("wf_import_batch")
    op.drop_table("wf_cost_category")
    op.drop_index("idx_ms_task_project_outline", table_name="ms_task")
    op.drop_index("idx_ms_task_project_id_display", table_name="ms_task")
    op.drop_table("ms_task")
    op.drop_index("idx_wf_resource_node_parent", table_name="wf_resource_node")
    op.drop_table("wf_resource_node")
    op.drop_table("wf_planning")
    op.drop_table("wf_inflation_rate")
    op.drop_table("wf_estimate")
    op.drop_table("wf_cost_type")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("idx_ms_project_name", table_name="ms_project")
    op.drop_table("ms_project")
    # ### end Alembic commands ###
